config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users, only: [:index, :destroy] do
    member do
      get :approve, :unapprove
    end
  end

  resources :campuses, only: [:index, :show], param: :code
  resources :contests, only: [:index, :show], param: :nth do
    resources :prize_histories, only: [:show], param: :region_code
    resources :brackets, only: [:show], param: :region_code
  end
  # resources :contest_entries, only: [:index]
  resource :statistics, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'home'
    end
  end
  resources :robots, only: [:show, :edit, :update], param: :code do
    resource  :robot_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :prize_histories,  only: [:new, :create, :edit, :update, :destroy]
    resources :games, param: :code
    resource  :advancement_history, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :download, only: :index

  # get 'draw_bracket', to: 'games#draw_bracket'

  resources :round_names, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get'
    end
  end

end

app/models/contest.rb
class Contest < ApplicationRecord
  module Constant
    NO_CONTEST = Contest.new(
      nth: 0, year: 0, name: "大会なし"
    )
  end
  
  has_many :robots, foreign_key: :contest_nth, primary_key: :nth, dependent: :destroy
  has_one :contest_entry, foreign_key: :nth, primary_key: :nth

  #==validates

  validates :name, presence: true, length:{ maximum:255 }
  validates :nth,  presence: true, uniqueness: true
  validates :year, presence: true

  #== scopes

  scope :on_page, -> page { paginate(page: page, per_page: 50) }
  scope :order_default, -> { order("nth desc") }
  scope :without_no_contest, -> { where.not(nth: Constant::NO_CONTEST.nth) }
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def index
    @contests = Contest.without_no_contest.order_default.on_page(params[:page])
  end

  def show
    @contest = Contest.find_by(nth: params[:nth])
    @robots = @contest.robots.includes(:campus).order_default.on_page(params[:page])
    @regions = Region.where("code <= 8")
  end
end

app/helpers/contests_helper.rb
module ContestsHelper

  def link_to_prior_contest(contest_nth)
    if contest_nth.to_i > 1 then # It's a hard code! But never changed.
      link_to fa_icon("chevron-left", text: "前回"),
        contest_path(
          nth: (contest_nth.to_i - 1).to_s
        )
    end
  end

  def link_to_posterior_contest(contest_nth)
    # 大会なしが含まれるため大会回数より一つレコードが多い。
    # if contest_nth.to_i < Contest.count - 1 then
    # 上記では大会数をだけ得るのにDBへアクセスしていまい、遅くなるので、
    # 下記のハードコーディングを採用し続けることにした。
    # configディレクトリなどにあるファイルで設定したいところであるが、
    # 代替ががでるまではこの方法にしておく。
    if contest_nth.to_i < 31 then # It's a hard code! Propose alternative ways!
      link_to fa_icon("chevron-right", text: "次回"),
        contest_path(
          nth: (contest_nth.to_i + 1).to_s
        )
    end
  end

end

app/views/contests/index.html.erb
<% provide(:title, "大会一覧") %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @contests, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>回</th>
          <th>年</th>
          <th>大会名</th>
        </tr>
      </thead>
      <tbody>
        <% @contests.each do |contest| %>
          <tr>
            <td align="right"><%= contest.nth %></td>
            <td><%= contest.year %></td>
            <td><%= link_to contest.name, contest_path(contest.nth) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @contests, inner_window: 2, outer_window: 0  %>
  </div>
</div>

app/views/contests/show.html.erb
<% provide(:title, @contest.name) %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <div class="pull-left">
      <p><%= link_to_prior_contest params[:nth] %></p>
    </div>
    <div class="pull-right">
      <p><%= link_to_posterior_contest params[:nth] %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h4>大会結果</h4>
    <%
      # 第1回から第3回まで地区予選はない
      if @contest.nth < 4 then
        concat link_to "全国大会", contest_prize_history_path(
          contest_nth: @contest.nth, region_code: 0)
      else
        @regions.each do |region|
          sfx = region.code == 0 ? "大会" : "地区大会"
          concat link_to "#{region.name}#{sfx}",
            contest_prize_history_path(contest_nth: @contest.nth,
              region_code: region.code)
          concat "<br />".html_safe
        end
      end
    %>
  </div>
</div>
<br />

<div class="row">
  <div class="col-lg-12">
    <div class="pull-left">
      <p><%= link_to_prior_contest params[:nth] %></p>
    </div>
    <div class="pull-right">
      <p><%= link_to_posterior_contest params[:nth] %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @robots, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h4>出場ロボット</h4>
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>キャンパス</th>
          <th>ロボット名</th>
          <th>カナ</th>
          <th>チーム</th>
        </tr>
      </thead>
      <tbody>
        <% @robots.each do |robot| %>
          <tr>
            <td><%= link_to robot.campus.abbreviation,
              campus_path(robot.campus.code) %></td>
            <td><%= link_to robot.name.truncate(SHORTENING_LEN),
              robot_path(robot.code) %></td>
            <td><%= robot.kana.truncate(SHORTENING_LEN) %></td>
            <td><%= robot.team %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @robots, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="pull-left">
      <p><%= link_to_prior_contest params[:nth] %></p>
    </div>
    <div class="pull-right">
      <p><%= link_to_posterior_contest params[:nth] %></p>
    </div>
  </div>
</div>