config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users, only: [:index, :destroy] do
    member do
      get :approve, :unapprove
    end
  end

  resources :campuses, only: [:index, :show], param: :code
  resources :contests, only: [:index, :show], param: :nth do
    resources :prize_histories, only: [:show], param: :region_code
    resources :brackets, only: [:show], param: :region_code
  end
  # resources :contest_entries, only: [:index]
  resource :statistics, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'home'
    end
  end
  resources :robots, only: [:show, :edit, :update], param: :code do
    resource  :robot_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :prize_histories,  only: [:new, :create, :edit, :update, :destroy]
    resources :games, param: :code
    resource  :advancement_history, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :download, only: :index

  # get 'draw_bracket', to: 'games#draw_bracket'

  resources :round_names, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get'
    end
  end

end

app/models/robot.rb
class Robot < ApplicationRecord
  module Constant
    NO_ROBOT = Robot.new( # このまま使われなかったらリファクタリング時に削除すべき
      code: 100000000, contest_nth: 0, campus_code: 0,
      name: "", kana: "", name_alias: "", kana_alias: "", memo: ""
    )
  end

  belongs_to :contest,             foreign_key: :contest_nth, primary_key: :nth
  belongs_to :campus,              foreign_key: :campus_code, primary_key: :code
  has_one    :robot_condition,     foreign_key: :robot_code,  primary_key: :code
  has_many   :prize_histories,     foreign_key: :robot_code,  primary_key: :code,
    dependent: :destroy
  #accepts_nested_attributes_for :prize_histories
  has_one    :advancement_history, foreign_key: :robot_code,  primary_key: :code

  #==validates

  validates :code,        presence: true, uniqueness: true
  validates :contest_nth, presence: true
  validates :campus_code, presence: true
  validates :team,       allow_blank: true, length:{ maximum:255 }, format: { :with => /(A|B)/i }
  validates :name,                          length:{ maximum:255 }, presence: true
  validates :kana,       allow_blank: true, length:{ maximum:255 }
  validates :name_alias, allow_blank: true, length:{ maximum:255 }
  validates :kana_alias, allow_blank: true, length:{ maximum:255 }
  validates :memo,       allow_blank: true, length:{ maximum:255 }

  #== scopes

  scope :on_page, -> page { paginate(page: page, per_page: 60) }
  scope :order_default, -> { order("contest_nth asc, campus_code asc, team asc, code asc") }
  scope :order_csv, -> { order(code: :asc) }

  def self.team_choices
    [["分からないまたはAB区別なし",""],["Ａチーム","A"],["Ｂチーム","B"]]
  end

  def to_key
    ["#{code}"]
  end

  def to_param
    "#{code}"
  end

  def self.csv_headers
    # UTF-8出力される
    [ "ロボットコード", "回", "キャンパスコード", "A/B", "ロボット名", "ヨミガナ", "別名", "別名ヨミガナ", "メモ" ]
  end

  def self.csv_column_syms
    [ :code, :contest_nth, :campus_code, :team, :name, :kana, :name_alias, :kana_alias, :memo ]
  end

  # 特別な#to_csvをオーバーライド
  def self.to_csv(options = {})
    codes = []
    codes << Game::Constant::NO_OPPONENT.code
    codes << Game::Constant::NO_WINNER.code
    CSV.generate(headers: true, force_quotes: true) do |csv|
      csv << csv_headers
      where.not(code: codes).each do |record|
        csv << csv_column_syms.map{ |attr| "#{record.send(attr).to_s}" }
      end
    end
  end

end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :admin_user, only: :index

  def show
    @robot = Robot.find_by(code: params[:code])
    @games = Game.where(left_robot_code: params[:code]).or(
      Game.where(right_robot_code: params[:code])).order(
        "games.region_code desc, games.code asc")
    @prize_histories = PrizeHistory.includes(:robot).where(
      robot_code: params[:code]).includes(:prize).order_default
  end

  def edit
    @robot = Robot.find_by(code: params[:code])
  end

  def update
    @robot = Robot.find_by(code: params[:code])
    if @robot.update_attributes(robot_params) then
      flash[:success] = "ロボット情報の編集成功"
      redirect_to robot_url(code: @robot.code)
    else
      render 'edit'
    end
  end

  private

  def robot_params
    params.require(:robot).permit(
      :name, :kana, :name_alias, :kana_alias, :team, :memo
    )
  end

end

app/helpers/robots_helper.rb
module RobotsHelper
  # ノックアウト方式だけではない予選がある大会もあるのでこのcaseで分類する方式を採用
  def game_name(hash:)
    round_name =
      RoundName.find_by(
        contest_nth: hash["contest_nth"],
        region_code: hash["region_code"],
        round: hash["round"]
      ) ||
      RoundName.new(
        name: "未定義"
      )
    
    # 回戦
    a = "#{round_name.name}"

    # リーグ
    case hash["contest_nth"].to_i
    when 31
      case hash["region_code"].to_i
      when 1..8 # 第31回は地区のみリーグ戦実施
        case round_name.name
        when "予選"
          case hash["league"].to_i
          when 0
            a += "リーグ不明"
          when 1..5
            a += "リーグ" + ("A".ord + hash["league"].to_i - 1).chr
          else
            a += "リーグ異常値"
          end
        end
      end
    end

    # 試合
    if round_name.name != "決勝" then
      a += " 第#{hash["game"]}試合"
    end
    a
  end
end

app/views/robots/edit.html.erb
<% provide(:title, "ロボット情報の編集") %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @robot do |f| %>

      <%= render 'shared/error_messages', obj: @robot %>

      <%= f.label :name, "ロボット名" %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :kana, "ヨミガナ" %>
      <%= f.text_field :kana, class: 'form-control' %><br>

      <%= f.label :name_alias, "ロボット名別名" %>
      <%= f.text_field :name_alias, class: 'form-control' %><br>

      <%= f.label :kana, "別名ヨミガナ" %>
      <%= f.text_field :kana_alias, class: 'form-control' %><br>

      <%= f.label :team, "チーム" %><br>
      <%= select :robot, :team, Robot.team_choices, class: 'form-control' %><br><br>
      
      <%= f.label :memo, "特記事項" %><br>
      <%= f.text_field :memo, class: 'form-control' %><br><br>

      <%= f.submit "更新", class: "btn btn-primary",
        data: { disable_with: '処理中・・・' } %><br><br>
    <% end %>

  </div>
</div>

app/views/robots/show.html.erb
<% provide(:title, @robot.name) %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <div align="right">
      <%= link_to fa_icon("pencil-square ", text:"編集"), edit_robot_path %>
    </div>
    <table class="table table-striped table-condensed">
      <tbody>
        <tr>
          <td>ヨミガナ：</td>
          <td><%= @robot.kana %></td>
        </tr>
        <% if @robot.name_alias.present? %>
        <tr>
          <td>別名：</td>
          <td><%= @robot.name_alias %></td>
        </tr>
        <tr>
          <td>別名ヨミガナ：</td>
          <td><%= @robot.kana_alias %></td>
        </tr>
        <% end %>
        <tr>
          <td>チーム：</td>
          <td><%= @robot.team %></td>
        </tr>
        <% if @robot.memo.present? %>
        <tr>
          <td>特記事項：</td>
          <td><%= @robot.memo %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h4>全国大会進出情報</h4>
    <% if !@robot.advancement_history.blank? then %>
    <div align="right">
      <%=
        link_to fa_icon("pencil-square", text:"編集"),
        edit_robot_advancement_history_path(@robot.code)
      %>
      または
      <%=
        link_to fa_icon("trash", text:"削除"),
        robot_advancement_history_path(@robot.code), :method => :delete,
        data: {confirm: "削除しますか？"}
      %>
    </div>
    <% else %>
    <div align="right"><%=
      link_to fa_icon("pencil-square-o", text:"新規作成"),
      new_robot_advancement_history_path(@robot.code)
    %></div>
    <% end %>
    <table class="table table-striped table-condensed">
      <tbody>
        <% if !@robot.advancement_history.blank? then %>
        <tr>
          <td>進出ケース：</td>
          <td><%=
            Advancement.find_by(
              case: @robot.advancement_history.advancement_case
            ).case_name
          %></td>
        </tr>
        <% if @robot.advancement_history.decline then %>
        <tr>
          <td></td>
          <td>全国進出を辞退</td>
        </tr>
        <% end %>
        <tr>
          <td>メモ：</td>
          <td><%= @robot.advancement_history.memo %></td>
        </tr>
        <% else %>
        <tr>
          <td colspan=2>未登録／残念ながら全国大会進出叶わず</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= render "prize_histories/prize_histories", prize_histories: @prize_histories %>

<div class="row">
  <div class="col-lg-12">
    <h4>対戦成績</h4>
    <div align="right">
      <%= link_to fa_icon("pencil-square-o", text:"新規登録"),
        new_robot_game_path(robot_code: @robot.code) %>
    </div>
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>地区／全国</th>
          <th>試合</th>
          <th>対戦キャンパス</th>
          <th>A/B</th>
          <th>対戦チーム</th>
          <th>勝敗</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <%
            left_robot =
              Robot.joins(:campus).find_by(code: game.left_robot_code) ||
                Game::Constant::NO_OPPONENT
            right_robot =
              Robot.joins(:campus).find_by(code: game.right_robot_code) ||
                Game::Constant::NO_OPPONENT
            opponent = @robot.code != left_robot.code ? left_robot : right_robot
          %>
          <tr>
            <td><%= game.region.name %></td>
            <td>
              <%=
                link_to game_name(hash: game),
                robot_game_path(robot_code: left_robot.code, code: game.code) 
              %>
            </td>
            <% if opponent.campus.code != Campus::Constant::NO_CAMPUS.code %>
            <td>
              <%=
                link_to opponent.campus.abbreviation,
                  campus_path(opponent.campus.code)
              %>
            </td>
            <td><%= opponent.team %></td>
            <td><%= link_to opponent.name.truncate(SHORTENING_LEN),
              robot_path(opponent.code) %></td>
            <% else %>
            <td></td>
            <td></td>
            <td><%= opponent.name.truncate(SHORTENING_LEN) %></td>
            <% end %>
            <td>
              <% # 出来ればモデルと共用のヘルパーメソッド化すべき
                case game.winner_robot_code
                when Game::Constant::NO_WINNER.code then
                  case opponent.code
                  when Game::Constant::NO_OPPONENT.code then
                    concat "単独競技につき勝ち負けなし"
                  else
                    concat "両者失格"
                  end
                else
                  case opponent.code
                  when Game::Constant::NO_OPPONENT.code then
                    concat "不戦勝"
                  else
                    if @robot.code == game.winner_robot_code then
                      concat "勝ち"
                    else
                      concat "負け"
                    end
                  end
                end
              %>
            </td>
            <td align="right">
              <%= link_to fa_icon("pencil-square", text:"編集"),
                edit_robot_game_path(robot_code: @robot.code, code: game.code) %>
              <%= link_to fa_icon("trash", text:"削除"),
                robot_game_path(robot_code: @robot.code, code: game.code),
                  :method => :delete, data: {confirm: "削除しますか？"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h4>現存情報</h4>
    <% if !@robot.robot_condition.blank? then %>
    <div align="right">
      <%= link_to fa_icon("pencil-square", text:"編集"),
        edit_robot_robot_conditions_path(@robot.code) %>
      または
      <%= link_to fa_icon("trash", text:"逸失に変更"),
        robot_robot_conditions_path(@robot.code), :method => :delete,
        data: {confirm: "逸失に変更しますか？"} %>
    </div>
    <% else %>
    <div align="right">
      <%= link_to fa_icon("pencil-square-o", text:"現存に変更"),
        new_robot_robot_conditions_path(@robot.code) %>
    </div>
    <% end %>
    <table class="table table-striped table-condensed">
      <tbody>
        <tr>
          <td>現況：</td>
          <% if !@robot.robot_condition.blank? then %>
          <td>現存</td>
          <% else %>
          <td>逸失</td>
          <% end %>
        </tr>
        <% if !@robot.robot_condition.blank? then %>
        <tr>
          <td></td>
          <% if @robot.robot_condition.fully_operational then %>
          <td>動態保存</td>
          <% else %>
          <td>静態保存</td>
          <% end %>
        </tr>
        <tr>
          <td></td>
          <% if !@robot.robot_condition.restoration then %>
          <td>オリジナル</td>
          <% else %>
          <td>復刻</td>
          <% end %>
        </tr>
        <tr>
          <td></td>
          <% if !@robot.robot_condition.memo.blank? then %>
          <td><%= @robot.robot_condition.memo %></td>
          <% else %>
          <td></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>