config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users, only: [:index, :destroy] do
    member do
      get :approve, :unapprove
    end
  end

  resources :campuses, only: [:index, :show], param: :code
  resources :contests, only: [:index, :show], param: :nth do
    resources :prize_histories, only: [:show], param: :region_code
    resources :brackets, only: [:show], param: :region_code
  end
  # resources :contest_entries, only: [:index]
  resource :statistics, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'home'
    end
  end
  resources :robots, only: [:show, :edit, :update], param: :code do
    resource  :robot_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :prize_histories,  only: [:new, :create, :edit, :update, :destroy]
    resources :games, param: :code
    resource  :advancement_history, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :download, only: :index

  # get 'draw_bracket', to: 'games#draw_bracket'

  resources :round_names, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get'
    end
  end

end

app/models/advancement_history.rb
class AdvancementHistory < ApplicationRecord
  belongs_to :contest,     foreign_key: :contest_nth,      primary_key: :nth
  belongs_to :region,      foreign_key: :region_code,      primary_key: :code
  belongs_to :campus,      foreign_key: :campus_code,      primary_key: :code
  belongs_to :robot,       foreign_key: :robot_code,       primary_key: :code
  belongs_to :advancement, foreign_key: :advancement_case, primary_key: :case

  validates :robot_code,        presence: true #, uniqueness: true
  # validates :decline,           inclusion: { in: [true, false] }

  scope :order_default, -> { order(
    contest_nth: :asc,
    region_code: :asc,
    campus_code: :asc,
    robot_code: :asc,
  ) }
  scope :order_csv, -> { order(robot_code: :asc) }

  def self.csv_headers
    # UTF-8出力される
    [
      "回", "地区", "キャンパスコード", "ロボットコード", "進出ケース",
      "辞退", "メモ"
    ]
  end

  def self.csv_column_syms
    [
      :contest_nth, :region_code, :campus_code, :robot_code, :advancement_case,
      :decline, :memo
    ]
  end
end

app/controllers/advancement_histories_controller.rb
class AdvancementHistoriesController < ApplicationController

  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  # before_action :admin_user, only: :index
  before_action :set_robot, only: [:new, :create, :edit, :update, :destroy]

  def new
  end

  def create
    params = advancement_history_params
    params["contest_nth"] = @robot.contest_nth
    params["region_code"] = @robot.campus.region_code
    params["campus_code"] = @robot.campus.code
    if @robot.create_advancement_history(params) then
      flash[:success] = "全国大会進出情報の新規作成成功"
      redirect_to robot_url(code: @robot.code)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @robot.advancement_history.update_attributes(advancement_history_params)
    then
      flash[:success] = "全国大会進出情報の編集成功"
      redirect_to robot_url(code: @robot.code)
    else
      render :edit
    end
  end

  def destroy
    @robot.advancement_history.destroy
    redirect_to robot_path(code: @robot.code)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_robot
    @robot = Robot.find_by(code: params[:robot_code])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def advancement_history_params
    params.require(:advancement_history).permit(
      :robot_code, :advancement_case, :decline, :memo
    )
  end

end

app/helpers/advancement_histories_helper.rb
module AdvancementHistoriesHelper
end

app/views/advancement_histories/_advancement_histories.html.erb
<div class="row">
  <div class="col-lg-12">
    <h4>全国大会進出情報</h4>
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>回</th>
          <th>大会名</th>
          <th>進出ケース</th>
          <th>ロボット名</th>
        </tr>
      </thead>
      <tbody>
      <% advancement_histories.present? &&
        advancement_histories.each do |history| %>
        <tr>
          <td align="right"><%= history.contest.nth %></td>
          <td><%= history.contest.name %></td>
          <td><%= history.advancement.case_name %></td>
          <td>
            <%= link_to history.robot.name.truncate(SHORTENING_LEN),
              robot_path(history.robot.code) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/advancement_histories/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for robot.advancement_history || AdvancementHistory.new(robot_code: robot.code),
      :url=>{:action => action} do |f| %>

      <%= render 'shared/error_messages', obj: robot %>

      <%= f.label :advancement_case, "進出ケース" %>：
      <%=
        f.collection_select :advancement_case, Advancement.all, :case, :case_name
      %>
      <br /><br />

      <%= f.label :decline, "辞退" %>：
      <%= f.check_box :decline, {}, "true", "false" %><br />

      <%= f.label :memo, "特記事項" %>：
      <%= f.text_field :memo, class: 'form-control' %><br />

      <%= f.submit button_label, class: "btn btn-primary",
        data: { disable_with: '処理中・・・' } %><br /><br />
    <% end %>

  </div>
</div>

app/views/advancement_histories/edit.html.erb
<% provide(:title, "全国大会進出情報の編集") %>

<%= render "shared/title", title: (yield :title) %>

<h4>ロボット名：<%= label_tag "", @robot.name, class: "robot_name" %></h4><br>

<%= render "form", robot: @robot, action: :update, button_label: "更新" %>

app/views/advancement_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advancement Histories</h1>

<table>
  <thead>
    <tr>
      <th>Robot code</th>
      <th>Case code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advancement_histories.each do |advancement_history| %>
      <tr>
        <td><%= advancement_history.robot_code %></td>
        <td><%= advancement_history.advancement_code %></td>
        <td><%= link_to 'Show', advancement_history %></td>
        <td><%= link_to 'Edit', edit_advancement_history_path(advancement_history) %></td>
        <td><%= link_to 'Destroy', advancement_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advancement History', new_advancement_history_path %>

app/views/advancement_histories/new.html.erb
<% provide(:title, "全国大会進出情報の新規作成") %>

<%= render "shared/title", title: (yield :title) %>

<h4>ロボット名：<%= label_tag "", @robot.name, class: "robot_name" %></h4><br>

<%= render "form", robot: @robot, action: :create, button_label: "新規作成" %>

app/views/advancement_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Robot code:</strong>
  <%= @advancement_history.robot_code %>
</p>

<p>
  <strong>Case code:</strong>
  <%= @advancement_history.advancement_code %>
</p>

<%= link_to 'Edit', edit_advancement_history_path(@advancement_history) %> |
<%= link_to 'Back', advancement_histories_path %>