config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users, only: [:index, :destroy] do
    member do
      get :approve, :unapprove
    end
  end

  resources :campuses, only: [:index, :show], param: :code
  resources :contests, only: [:index, :show], param: :nth do
    resources :prize_histories, only: [:show], param: :region_code
    resources :brackets, only: [:show], param: :region_code
  end
  # resources :contest_entries, only: [:index]
  resource :statistics, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'home'
    end
  end
  resources :robots, only: [:show, :edit, :update], param: :code do
    resource  :robot_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :prize_histories,  only: [:new, :create, :edit, :update, :destroy]
    resources :games, param: :code
    resource  :advancement_history, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :download, only: :index

  # get 'draw_bracket', to: 'games#draw_bracket'

  resources :round_names, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'get'
    end
  end

end

app/models/contest_entry.rb
class ContestEntry < ApplicationRecord
  belongs_to :contest, foreign_key: :contest_nth, primary_key: :nth

  scope :on_page, -> page { paginate(page: page, per_page: 50) }
  scope :order_default, -> { order("contest_nth asc") }
end

app/controllers/contest_entries_controller.rb
class ContestEntriesController < ApplicationController
  def index
    @contest_entries = ContestEntry.joins(:contest).order_default.on_page(params[:page])
  end

  def show
    #@contest_entries = ContestEntry.find(params[:id])
    #@robots = @contest.robots.includes(:campus).order_default.on_page(params[:page])
  end
end

app/helpers/contest_entries_helper.rb
module ContestEntriesHelper
end

app/views/contest_entries/index.html.erb
<% provide(:title, "参加統計") %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @contest_entries, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="container-fluid">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th class="text-center">回</th>
          <th class="text-center">年</th>
          <th class="text-center">大会名</th>
          <th class="text-center">学校数</th>
          <th class="text-center">キャンパス数</th>
          <th class="text-center">チーム数</th>
        </tr>
      </thead>
      <tbody>
        <% @contest_entries.each do |entry| %>
          <tr>
            <td class="text-right"><%= entry.contest.nth %></td>
            <td class="text-right"><%= entry.contest.year %></td>
            <td class="text-left" ><%= link_to entry.contest.name, contest_path(entry.contest.nth)%></td>
            <td class="text-right"><%= entry.school %></td>
            <td class="text-right"><%= entry.campus %></td>
            <td class="text-right"><%= entry.team %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @contests, inner_window: 2, outer_window: 0  %>
  </div>
</div>

app/views/contest_entries/show.html.erb
<h1>ContestEntries#show</h1>
<p>Find me in app/views/contest_entries/show.html.erb</p>